name = input()
age = int(input())
course_rating = float(input())
print(f"Student: {name}")
print(f"Age: {age}")
print(f"Rating: {course_rating}")
print(type(name))
print(type(age))
print(type(course_rating))
